# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: kube-system
stringData:
    email: ENC[AES256_GCM,data:+00c+3KwkYwr1wiO15pjZTFv9I0817U=,iv:ZRYRWX65q9CKoJoEOjdoqYwQtmYHys/WS7II7Gi0NzA=,tag:QEElAXigOvmkT6Rpr6NQWA==,type:str]
    api-key: ENC[AES256_GCM,data:0ZNYNJtrWmVPBBoJA/NGmDtICi6NtYErapEFBS4YxTefyYl0yA==,iv:JfwT7YKNa26F1abrV+Ar71vO8uWtbqD8XDQknSBwpdA=,tag:P4VrFXDhHz2C4MM+TCJgAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ew65ujl09uhlaqyhrl4hsxc2dy8xwfyzatrfq9yhlwax0qv0ersd0cq49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZU0yUmxhMTdxeFpzd0Rv
            bmlrcE5relRVZXdiVDllR0xaS2w1SldlY25rClNmMkFYUlVqNzlhR09RbVVYeE5R
            QnEvelk4V2lGQk5PcFFoeFlkMWFFK2sKLS0tIG5LTXhVb2VTYzZiWXh1aGwxbkpl
            OTNqenJMSkhzMTNrMGRkZTE2aUtSUk0K9fM4koTnpHHzsDabe15IHrz82IvNo6jR
            AakQfH1RDR4M5flQwlhNV5KEE5wbCSOcAdzYwtmbRwodWm8brL0wDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T15:56:10Z"
    mac: ENC[AES256_GCM,data:wx+9+anrKyPpJhCxp/7QdypjcpEscHKAr3X0AMbkuD8kBXCb0uWAx8L02NW5LNtMJRMdtTL6C236uqgZKb8gtpDA+1gZMQBVQSBu5/1+ZVbClI4BzrtsaJ9UthOu24fGsPoX1V/dYmX6BoHraUjngBa+I3R+O6A6k/O4Gc6sGWU=,iv:/pHfOlG2GzjCnosPG87LHuqWvP8T4rDmKRH8KgQquOM=,tag:YCuHXF2q6D78GrwdABmA1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
