kind: Secret
ansible_user: ENC[AES256_GCM,data:+Ng=,iv:E+Q1MxJ4nxSN2lGilh9B97RZxkdwsuaIbShJM2D992Y=,tag:ZRCe+Qp04zbifWfAGrYMZw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8O5A0kHH2j+jL6Q=,iv:EIs+obgNg96wDWkBIfAb92nWEcSG5ktXHneJ1JLS964=,tag:PDh85HGvXmUXoASYop1x9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ew65ujl09uhlaqyhrl4hsxc2dy8xwfyzatrfq9yhlwax0qv0ersd0cq49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZmh1T1JDamVCUlFVSlgw
            aEYwak12dk9VenJyTkNzTUlXYUg2Rm9RQ0VRCmRucktUZjExLzFmSXBRZ1NRSm43
            YTRNMkF0cGFtelJFZFljSGcwbjV2NjgKLS0tIHdiendNeEpWVXBrOS9FeDZ1V1E1
            MzJ1QUZWYmU2bTFlQ1JsWWtRMUhVbDAKc+6GyDdnctUxlSUxuqsBXqs8kj0QCg1L
            dbtNQUErfPV/eX3nWxWLBzIZwWG2NMtxBuDFZG2uGqB10WtEf7KxaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T15:56:11Z"
    mac: ENC[AES256_GCM,data:mY+VFGK03sivMy3cvfri74cBf5nI92epQPuMUDOZ9j4n6hEm1kClNBwB28bpOzQuoqZ3ygj3Rpld+8cy1TwJpNkwHZRa5jWwDb79o3iDcu4WE5ThToHwbSxhmbNu4P6A8CT2nNkF96tjXzELrMpb3bsVZs6/9xclKZCVISVVFkE=,iv:Gk72ulJTAUe8Zlv5THj+ep7F0IxZOd/VyB7/hWkj/xY=,tag:o95r7PXC8sp2H8r/474XzQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
