---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 192.168.86.220-192.168.86.230
  METALLB_K8S_GATEWAY_ADDR: 192.168.86.220
  METALLB_INGRESS_ADDR: 192.168.86.221
