# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:hJSsdskGmD6BUo9fU8GUc9u3H179B1KfO0xpWS+CeZVltYnr3g==,iv:MZennoY6UXb6nFZaqtnLKmJHVOz7CJpkR6HgxBIpefI=,tag:rn1rwqC8goWdp5v1R0hZdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ew65ujl09uhlaqyhrl4hsxc2dy8xwfyzatrfq9yhlwax0qv0ersd0cq49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR3NWU3RqVlEvK3FyaFFG
            ZFJxRVJlL2Y4aDBjRGZPdjdNUlluNXJTUzJnCkg3WnRySlBLcWtnL1djNFJ2RDE0
            b280NFJBbGFtWjBWODNOWG0vVzRCa2MKLS0tIGF4OEg0SS9JZWplc2hRRmlNaHU4
            K1duekxDNmhFZGpRY2h1NHpqV3lUQVkKJvK/lyzrxrwYpv9rEl8HYwrN8aJOo/rQ
            fX1G2ZuqSc9teMY3/uTfLNKqpPVTyihLWLVXIGJpSfnoQkN9HQAVJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T15:56:10Z"
    mac: ENC[AES256_GCM,data:igkxKU0BBNoVNYnqJyHCAfrm7FqoELDUkIYwmzzWUhW2Wj2JZi6xqjIgUMHhbK5xwcmjmlM5Px3qVFJIHw+ip7GmFRWnkaAZoBCbLzYvM0G1YPf+U9LDmPKOdONbeZVoBkzp2nNHpM1tLslT6gCE3cMud2IEXDNfVn1rW4T/zD8=,iv:Ip8FsiEfpPrt7xt97VfZjZFh2H2QMCf35CxmC0qZQpM=,tag:ThzRQM2V/28LDMvYn4pYCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
